# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on: [push, pull_request]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64


      - name: Login to Docker
        run: |
            docker login --username=${{ secrets.USERNAME_ALI }} registry.cn-hangzhou.aliyuncs.com -p ${{ secrets.PASSWORD_ALI }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          context: operator
          file: operator/Dockerfile-arm64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/nacos-wyd/nacos-operator:v1.0.0-dbug-arm64
          labels: inspurwyd
          
